django_app/core/urls.py
import logging

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import cookie_views, generic_views
from .views.generic_views import PingSessionView, RedirectBaseDomainView

public_urls = [
    path("", RedirectBaseDomainView.as_view(), name="initial_redirect_view"),
    path("give-feedback/", include("feedback.urls")),
    path("healthcheck/", include("healthcheck.urls")),
    path("throw_error/", lambda x: 1 / 0),
    path("apply/", include("apply_for_a_licence.urls")),
    path("cookies-policy", cookie_views.CookiesConsentView.as_view(), name="cookies_consent"),
    path("privacy-notice", generic_views.PrivacyNoticeView.as_view(), name="privacy_notice"),
    path("hide_cookies", cookie_views.HideCookiesView.as_view(), name="hide_cookies"),
    path("reset_session", generic_views.ResetSessionView.as_view(), name="reset_session"),
    path("ping_session/", PingSessionView.as_view(), name="ping_session"),
    path("accessibility-statement", generic_views.AccessibilityStatementView.as_view(), name="accessibility_statement"),
    path("help-support", generic_views.HelpAndSupportView.as_view(), name="help_and_support"),
    path("staff-sso/", include("authbroker_client.urls")),
    path("authentication/", include("authentication.urls")),
]

private_urls = [
    path("view/", include("view_a_licence.urls")),
]

if settings.SHOW_ADMIN_PANEL:
    private_urls.append(path("admin/", admin.site.urls))

if settings.INCLUDE_PRIVATE_URLS:
    logging.info("Include private urls")
    urlpatterns = public_urls + private_urls
else:
    logging.info("Excluding private urls")
    urlpatterns = public_urls

if "debug_toolbar" in settings.INSTALLED_APPS:
    # checking if we have debug_toolbar installed
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

django_app/feedback/urls.py
from django.urls import path

from . import views

app_name = "feedback"

urlpatterns = [
    path("", views.ProvideFullFeedbackView.as_view(), name="collect_full_feedback"),
    path("feedback-sent", views.FeedbackDoneView.as_view(), name="feedback_done"),
]

django_app/feedback/models.py
from core.models import BaseModel
from django.contrib.postgres.fields import ArrayField
from django.db import models

from .choices import DidYouExperienceAnyIssues, RatingChoices


class FeedbackItem(BaseModel):
    rating = models.IntegerField(choices=RatingChoices.choices, blank=False)
    did_you_experience_any_issues = ArrayField(
        base_field=models.CharField(max_length=32, choices=DidYouExperienceAnyIssues.choices), blank=True, null=True
    )
    how_we_could_improve_the_service = models.TextField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    user_name = models.CharField(max_length=255, null=True, blank=True)
    user_email = models.EmailField(null=True, blank=True)

    def get_did_you_experience_any_issues_display(self) -> str:
        display_list = []
        if self.did_you_experience_any_issues:
            display_list += [dict(DidYouExperienceAnyIssues.choices)[value] for value in self.did_you_experience_any_issues]
        display = ",\n".join(display_list)
        return display

django_app/feedback/forms.py
from typing import Any

from core.forms.base_forms import BaseModelForm
from crispy_forms_gds.layout import Field, Fieldset, Layout, Size
from django import forms

from .choices import DidYouExperienceAnyIssues
from .crispy_fields import HTMLTemplate, get_field_with_label_id
from .models import FeedbackItem


class FeedbackForm(BaseModelForm):
    submit_button_text = "Submit"

    did_you_experience_any_issues = forms.MultipleChoiceField(
        choices=DidYouExperienceAnyIssues.active_choices(),
        widget=forms.CheckboxSelectMultiple,
        label="Select all that apply",
        required=False,
    )

    class Meta:
        model = FeedbackItem
        fields = ("rating", "did_you_experience_any_issues", "how_we_could_improve_the_service", "user_name", "user_email")
        labels = {
            "how_we_could_improve_the_service": "How could we improve the service? (optional)",
            "rating": "Overall, how satisfied did you feel with using this service?",
            "user_name": "Your name (optional)",
            "user_email": "Your email address (optional)",
        }
        widgets = {
            "rating": forms.RadioSelect,
        }

        error_messages = {
            "rating": {"required": "Select how satisfied you felt using this service"},
        }

    class Media:
        js = ["feedback/javascript/feedback.js"]
        css = {
            "all": ["feedback/stylesheets/feedback.css"],
        }

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields["rating"].choices.pop(0)
        self.helper.layout = Layout(
            Field.radios("rating", legend_size=Size.MEDIUM, legend_tag="h2"),
            Fieldset(
                Field.checkboxes("did_you_experience_any_issues", legend=""),
                legend="What did not work so well? (optional)",
                legend_size=Size.MEDIUM,
                legend_tag="h2",
                css_class="optional_question",
            ),
            Fieldset(
                get_field_with_label_id(
                    "how_we_could_improve_the_service",
                    label_id="how_we_could_improve_the_service-label",
                    field_method=Field.textarea,
                    rows=5,
                    label_size=Size.MEDIUM,
                    label_tag="h2",
                    max_characters=1200,
                    aria_describedby="how_we_could_improve_the_service-label",
                ),
                css_class="optional_question",
            ),
            Fieldset(
                HTMLTemplate("feedback/participate_in_user_research.html"),
                Field("user_name", context={"label_size": None}),
                Field("user_email", context={"label_size": None}),
            ),
        )

django_app/feedback/views.py
import logging

from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic import FormView, TemplateView

from .forms import FeedbackForm

logger = logging.getLogger(__name__)


class ProvideFullFeedbackView(FormView):
    """View for collecting full feedback from the user."""

    form_class = FeedbackForm
    template_name = "feedback/collect_feedback.html"

    def form_valid(self, form: FeedbackForm) -> HttpResponseRedirect:
        feedback_item = form.save()

        # adding the URL to the new feedback item
        if url := self.request.GET.get("url"):
            feedback_item.url = url
            feedback_item.save()

        return redirect("feedback:feedback_done")

    def form_invalid(self, form):
        logger.error("Feedback form is invalid", extra={"form_errors": form.errors})
        return super().form_invalid(form)


class FeedbackDoneView(TemplateView):
    template_name = "feedback/feedback_done.html"

django_app/feedback/templates/feedback/collect_feedback.html
{% extends "core/base.html" %}
{% load crispy_forms_tags crispy_forms_gds %}

{% block extra_css %}
    {{ form.media.css }}
{% endblock extra_css %}

{% block extra_js %}
    {{ block.super }}
    {{ form.media.js }}
{% endblock extra_js %}

{% block title %}Give feedback on the Apply for a Licence service{% endblock title %}
{% block column_content %}
    <form action="{% url 'feedback:collect_full_feedback' %}?url={{ request.GET.url }}" method="post" enctype='multipart/form-data' novalidate>
        <h1 class="govuk-heading-l">Give feedback on the Apply for a Licence service</h1>
        {% csrf_token %}
        {% crispy form %}
    </form>
{% endblock column_content %}

django_app/feedback/templates/feedback/feedback_disclaimer.html
<p class="govuk-body">We use feedback to help us improve the service and cannot respond to any requests for support you make on this form</p>

django_app/feedback/templates/feedback/feedback_done.html
{% extends 'core/base.html' %}

{% block title %}Feedback sent{% endblock title %}

{% block column_content %}
    <div class="govuk-panel govuk-panel--confirmation">
        <h1 class="govuk-panel__title">
            Feedback sent
        </h1>
    </div>
    <p class="govuk-body">Thank you for your feedback.</p>
    <p class="govuk-body">Your feedback will help us improve this service.</p>
{% endblock column_content %}

django_app/feedback/templates/feedback/participate_in_user_research.html
<h2 class="govuk-heading-m">Participating in further research</h2>
<p class="govuk-body">We're always improving our services and would like your help to make this one better. If you're happy for us to contact you about participating in further research, please leave your name and email address.</p>