django_app/core/urls.py
import logging

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import cookie_views, generic_views
from .views.generic_views import PingSessionView, RedirectBaseDomainView

public_urls = [
    path("", RedirectBaseDomainView.as_view(), name="initial_redirect_view"),
    path("give-feedback/", include("feedback.urls")),
    path("healthcheck/", include("healthcheck.urls")),
    path("throw_error/", lambda x: 1 / 0),
    path("apply/", include("apply_for_a_licence.urls")),
    path("cookies-policy", cookie_views.CookiesConsentView.as_view(), name="cookies_consent"),
    path("privacy-notice", generic_views.PrivacyNoticeView.as_view(), name="privacy_notice"),
    path("hide_cookies", cookie_views.HideCookiesView.as_view(), name="hide_cookies"),
    path("reset_session", generic_views.ResetSessionView.as_view(), name="reset_session"),
    path("ping_session/", PingSessionView.as_view(), name="ping_session"),
    path("accessibility-statement", generic_views.AccessibilityStatementView.as_view(), name="accessibility_statement"),
    path("help-support", generic_views.HelpAndSupportView.as_view(), name="help_and_support"),
    path("staff-sso/", include("authbroker_client.urls")),
    path("authentication/", include("authentication.urls")),
]

private_urls = [
    path("view/", include("view_a_licence.urls")),
]

if settings.SHOW_ADMIN_PANEL:
    private_urls.append(path("admin/", admin.site.urls))

if settings.INCLUDE_PRIVATE_URLS:
    logging.info("Include private urls")
    urlpatterns = public_urls + private_urls
else:
    logging.info("Excluding private urls")
    urlpatterns = public_urls

if "debug_toolbar" in settings.INSTALLED_APPS:
    # checking if we have debug_toolbar installed
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

django_app/view_a_licence/urls.py
from django.urls import path

from . import views

app_name = "view_a_licence"

urlpatterns = [
    path("", views.RedirectBaseViewerView.as_view(), name="initial_redirect_view"),
    path("view-all-applications", views.ApplicationListView.as_view(), name="application_list"),
    path("view-application/<str:reference>/", views.ViewALicenceApplicationView.as_view(), name="view_application"),
    path("manage-users/", views.ManageUsersView.as_view(), name="manage_users"),
    path("view-all-feedback/", views.ViewAllFeedbackView.as_view(), name="view_all_feedback"),
    path("view-feedback/<int:pk>", views.ViewFeedbackView.as_view(), name="view_feedback"),
    path("download-application/", views.DownloadPDFView.as_view(), name="download_application"),
]

django_app/apply_for_a_licence/models.py
# mypy: disable-error-code="attr-defined,misc"
import datetime
import uuid

from core.document_storage import PermanentDocumentStorage, TemporaryDocumentStorage
from core.models import BaseModel
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import QuerySet
from django.forms import model_to_dict
from django.utils import timezone
from django_countries.fields import CountryField
from utils.companies_house import get_formatted_address
from utils.s3 import store_document_in_permanent_bucket

from . import choices
from .types import Licensee
from .utils import get_file_s3_key


class Licence(BaseModel):
    """The chief model for the application for a licence. Represents an application"""

    business_registered_on_companies_house = models.CharField(
        choices=choices.YesNoDoNotKnowChoices.choices,
        max_length=11,
        blank=False,
    )
    licensing_grounds = ArrayField(models.CharField(choices=choices.LicensingGroundsChoices.choices), null=True)
    licensing_grounds_legal_advisory = ArrayField(models.CharField(choices=choices.LicensingGroundsChoices.choices), null=True)
    regimes = ArrayField(base_field=models.CharField(max_length=255), blank=False, null=True)
    reference = models.CharField(max_length=6)
    submitter_reference = models.CharField(max_length=255, blank=False, null=True)
    type_of_service = models.CharField(choices=choices.TypeOfServicesChoices.choices)
    professional_or_business_services = ArrayField(
        models.CharField(choices=choices.ProfessionalOrBusinessServicesChoices.choices), null=True
    )
    service_activities = models.TextField(blank=False, null=True)
    description_provision = models.TextField(blank=True, null=True)
    purpose_of_provision = models.TextField(blank=True, null=True)
    held_existing_licence = models.CharField(
        choices=choices.YesNoChoices.choices,
        blank=False,
        null=True,
    )
    existing_licences = models.TextField(null=True, blank=True)
    is_third_party = models.BooleanField(null=True, blank=False)
    who_do_you_want_the_licence_to_cover = models.CharField(
        max_length=255,
        choices=choices.WhoDoYouWantTheLicenceToCoverChoices.choices,
        blank=False,
        null=False,
    )

    applicant_user_email_address = models.EmailField(
        blank=True,
        null=True,
    )
    applicant_full_name = models.CharField(max_length=255, null=True, blank=False)
    applicant_business = models.CharField(max_length=300, verbose_name="Business you work for", blank=False, null=True)
    applicant_role = models.CharField(max_length=255, blank=False, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name="licence_applications")
    status = models.CharField(max_length=10, choices=choices.StatusChoices.choices, default=choices.StatusChoices.draft)
    submitted_at = models.DateTimeField(null=True, blank=True)
    do_you_want_to_add_another_recipient = models.BooleanField(null=True, blank=False)
    do_you_want_to_add_another_individual = models.BooleanField(null=True, blank=False)
    do_you_want_to_add_another_business = models.BooleanField(null=True, blank=False)
    submitted_documents_form = models.BooleanField(default=False, null=True, blank=False)

    def assign_reference(self) -> str:
        """Assigns a unique reference to this Licence object"""
        reference = uuid.uuid4().hex[:6].upper()
        if self.__class__.objects.filter(reference=reference).exists():
            return self.assign_reference()
        self.reference = reference
        return reference

    @property
    def recipients(self) -> "QuerySet[Organisation]":
        return self.organisations.filter(type_of_relationship=choices.TypeOfRelationshipChoices.recipient)

    def licensees(self) -> list[Licensee]:
        licensees = []

        if self.who_do_you_want_the_licence_to_cover == choices.WhoDoYouWantTheLicenceToCoverChoices.business:
            for organisation in self.organisations.filter(type_of_relationship=choices.TypeOfRelationshipChoices.business):
                licensees.append(
                    Licensee(
                        name=organisation.name,
                        address=organisation.registered_office_address,
                        label_name="Business",
                    )
                )
        elif self.who_do_you_want_the_licence_to_cover in [
            choices.WhoDoYouWantTheLicenceToCoverChoices.individual,
            choices.WhoDoYouWantTheLicenceToCoverChoices.myself,
        ]:
            for individual in self.individuals.all():
                licensees.append(
                    Licensee(
                        name=individual.full_name,
                        address=get_formatted_address(model_to_dict(individual)),
                        label_name="Individual",
                    )
                )

        return licensees

    def get_licensing_grounds_display(self) -> list[str]:
        if self.licensing_grounds:
            return [choices.LicensingGroundsChoices[value].label for value in self.licensing_grounds]
        else:
            return []

    def get_licensing_grounds_legal_advisory_display(self) -> list[str]:
        if self.licensing_grounds_legal_advisory:
            return [choices.LicensingGroundsChoices[value].label for value in self.licensing_grounds_legal_advisory]
        else:
            return []

    def get_professional_or_business_services_display(self) -> list[str]:
        if self.professional_or_business_services:
            return [
                choices.ProfessionalOrBusinessServicesChoices[value].label for value in self.professional_or_business_services
            ]
        else:
            return []

    def get_date_till_deleted(self) -> datetime.datetime:
        return self.created_at + datetime.timedelta(days=settings.DRAFT_APPLICATION_EXPIRY_DAYS)

    def is_expired(self) -> bool:
        """Returns True if the licence has been in draft for more than the set expiry days"""
        if self.status == choices.StatusChoices.draft:
            return timezone.now() > self.get_date_till_deleted()
        else:
            return False


class AddressMixin(models.Model):
    address_line_1 = models.CharField(max_length=200, blank=True, null=True)
    address_line_2 = models.CharField(max_length=200, blank=True, null=True)
    address_line_3 = models.CharField(max_length=200, blank=True, null=True)
    address_line_4 = models.CharField(max_length=200, blank=True, null=True)
    postcode = models.CharField(max_length=20, blank=True, null=True)
    country = CountryField(blank_label="Select country", blank=True, null=True)
    town_or_city = models.CharField(max_length=250, blank=True, null=True)
    county = models.CharField(max_length=250, null=True, blank=True)
    where_is_the_address = models.CharField(
        max_length=20, blank=False, null=True, choices=choices.WhereIsTheAddressChoices.choices
    )

    class Meta:
        abstract = True

    def readable_address(self) -> str:
        """Returns a formatted address string for the address fields of this model instance."""
        return get_formatted_address(model_to_dict(self))


class Organisation(BaseModel, AddressMixin):
    class Meta:
        ordering = ["created_at"]

    licence = models.ForeignKey("Licence", on_delete=models.CASCADE, blank=False, related_name="organisations")
    # two name fields required for the case of recipients
    name = models.CharField(null=True, blank=False)
    website = models.URLField(null=True, blank=True)
    do_you_know_the_registered_company_number = models.CharField(choices=choices.YesNoChoices.choices, blank=False, null=True)
    business_registered_on_companies_house = models.CharField(
        choices=choices.YesNoDoNotKnowChoices.choices, max_length=11, blank=False, null=True
    )
    registered_company_number = models.CharField(max_length=15, blank=True, null=True)
    registered_office_address = models.CharField(null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    additional_contact_details = models.CharField(blank=True, null=True)
    type_of_relationship = models.CharField(
        # only allow recipient, business, or named individuals employment details in this table
        choices=(
            (choices.TypeOfRelationshipChoices.recipient.value, choices.TypeOfRelationshipChoices.recipient.label),
            (choices.TypeOfRelationshipChoices.business.value, choices.TypeOfRelationshipChoices.business.label),
            (
                choices.TypeOfRelationshipChoices.named_individuals.value,
                choices.TypeOfRelationshipChoices.named_individuals.label,
            ),
        ),
        max_length=20,
        blank=False,
    )
    relationship_provider = models.TextField(
        blank=False, null=True, db_comment="what is the relationship between the provider and the recipient?"
    )
    status = models.CharField(
        max_length=10, choices=choices.EntityStatusChoices.choices, default=choices.EntityStatusChoices.draft
    )

    def readable_address(self) -> str:
        """If we have registered_office_address, use that instead of the address fields"""
        if self.registered_office_address:
            return self.registered_office_address
        else:
            return super().readable_address()

    def clear_address_data(self) -> None:
        """Clears the address data on the model instance"""
        self.address_line_1 = None
        self.address_line_2 = None
        self.address_line_3 = None
        self.address_line_4 = None
        self.postcode = None
        self.country = None  # type: ignore[assignment]
        self.town_or_city = None
        self.county = None
        self.where_is_the_address = None
        self.save()

django_app/feedback/models.py
from core.models import BaseModel
from django.contrib.postgres.fields import ArrayField
from django.db import models

from .choices import DidYouExperienceAnyIssues, RatingChoices


class FeedbackItem(BaseModel):
    rating = models.IntegerField(choices=RatingChoices.choices, blank=False)
    did_you_experience_any_issues = ArrayField(
        base_field=models.CharField(max_length=32, choices=DidYouExperienceAnyIssues.choices), blank=True, null=True
    )
    how_we_could_improve_the_service = models.TextField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    user_name = models.CharField(max_length=255, null=True, blank=True)
    user_email = models.EmailField(null=True, blank=True)

    def get_did_you_experience_any_issues_display(self) -> str:
        display_list = []
        if self.did_you_experience_any_issues:
            display_list += [dict(DidYouExperienceAnyIssues.choices)[value] for value in self.did_you_experience_any_issues]
        display = ",\n".join(display_list)
        return display

django_app/view_a_licence/models.py
# Create your models here.

django_app/view_a_licence/templates/view_a_licence/application_list.html
{% extends "core/base.html" %}
{% block cookie_banner %}{% endblock cookie_banner %}
{% block title %}Licence applications to provide sanctioned trade services{% endblock title %}
{% block back_button %}{% endblock back_button %}
{% block column_content %}
    <div>
        <h1 class="govuk-heading-l">
            Licence applications to provide sanctioned trade services
        </h1>
        <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">
    </div>
    <form method="get" action="{% url 'view_a_licence:application_list' %}" id="sort_form">
        {% csrf_token %}
        <div class="govuk-form-group">
            <label class="govuk-label" for="sort">Sort by
                <select class="govuk-select" id="sort_by" name="sort_by"
                        onchange="document.getElementById('sort_form').submit();">
                    <option value="newest" {% if selected_sort == "newest" %} selected {% endif %}>Date of report
                        (newest)
                    </option>
                    <option value="oldest" {% if selected_sort == "oldest" %} selected {% endif %}>Date of report
                        (oldest)
                    </option>
                </select></label>
        </div>
    </form>
    <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">

    {% for licence_application in object_list %}
        <h3 class="govuk-heading-s govuk-!-margin-bottom-2">
            <a href="{% url 'view_a_licence:view_application' reference=licence_application.reference %}" class="govuk-link">
                View licence application reference: {{ licence_application.reference }}
            </a></h3>
        <div class="govuk-body">
            <h3 class="govuk-heading-s govuk-summary-list__value">Purpose for providing the service</h3>
            {% include "apply_for_a_licence/partials/truncated_text.html" with text=licence_application.purpose_of_provision|linebreaksbr %}
        </div>
        <dl class="govuk-summary-list govuk-summary-list--no-border mb-1">
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key govuk-caption-m govuk-!-font-weight-regular">
                    Submitted by:
                </dt>
                <dd class="govuk-summary-list__value govuk-!-font-weight-bold">
                    {{ licence_application.applicant_full_name }}
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key govuk-caption-m govuk-!-font-weight-regular">
                    Proposed licensee:
                </dt>
                <dd class="govuk-summary-list__value govuk-!-font-weight-bold">
                    {% for licensee in licence_application.licensees %}
                        {{ licensee.name }}
                        {% if not forloop.last %}
                            <br>
                        {% endif %}
                    {% endfor %}
                </dd>
            </div>
            {% if licence_application.held_existing_licence %}
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key govuk-caption-m govuk-!-font-weight-regular">
                        Previous licence number:
                    </dt>
                    <dd class="govuk-summary-list__value govuk-!-font-weight-bold">
                        {{ licence_application.existing_licences | linebreaksbr }}
                    </dd>
                </div>
            {% endif %}
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key govuk-caption-m govuk-!-font-weight-regular">
                    Services being provided:
                </dt>
                <dd class="govuk-summary-list__value govuk-!-font-weight-bold">
                    {{ licence_application.get_type_of_service_display }}
                </dd>
            </div>
            <div class="govuk-summary-list__row">
                <dt class="govuk-summary-list__key govuk-caption-m govuk-!-font-weight-regular">
                    Submitted on:
                </dt>
                <dd class="govuk-summary-list__value govuk-!-font-weight-bold">
                    {{ licence_application.created_at }}
                </dd>
            </div>
            {% if licence_application.documents.count %}
                <div class="govuk-summary-list__row">
                    <dt class="govuk-summary-list__key govuk-caption-m govuk-!-font-weight-regular">
                        Files uploaded:
                    </dt>
                    <dd class="govuk-summary-list__value govuk-!-font-weight-bold">
                        {% for document in licence_application.documents.all %}
                            <a class="govuk-link" href="{{ document.url }}">{{ document.original_file_name }}</a>
                            {% if not forloop.last %}
                                <br>
                            {% endif %}
                        {% endfor %}
                    </dd>
                </div>
            {% endif %}
        </dl>
        <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible mb-1">
    {% endfor %}

    <nav class="govuk-pagination" aria-label="Pagination">
        {% if page_obj.has_previous %}
            <div class="govuk-pagination__prev">
                <a class="govuk-link govuk-pagination__link" href="?page={{ page_obj.previous_page_number }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}" rel="prev">
                    <svg class="govuk-pagination__icon govuk-pagination__icon--prev"
                         xmlns="http://www.w3.org/2000/svg" height="13" width="15" aria-hidden="true"
                         focusable="false" viewBox="0 0 15 13">
                        <path d="m6.5938-0.0078125-6.7266 6.7266 6.7441 6.4062 1.377-1.449-4.1856-3.9768h12.896v-2h-12.984l4.2931-4.293-1.414-1.414z"></path>
                    </svg>
                    <span class="govuk-pagination__link-title">
                        Previous<span class="govuk-visually-hidden"> page</span>
                    </span>
                </a>
            </div>
        {% endif %}

        <ul class="govuk-pagination__list">
            {% for i in page_obj.paginator.page_range %}
                {% if i == page_obj.number %}
                    <li class="govuk-pagination__item govuk-pagination__item--current">
                        <a class="govuk-link govuk-pagination__link" href="?page={{ i }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}" aria-label="Page {{ i }}" aria-current="page">
                            {{ i }}
                        </a>
                    </li>
                {% else %}
                    <li class="govuk-pagination__item">
                        <a class="govuk-link govuk-pagination__link" href="?page={{ i }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}" aria-label="Page {{ i }}">
                            {{ i }}
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>

        {% if page_obj.has_next %}
            <div class="govuk-pagination__next">
                <a class="govuk-link govuk-pagination__link" href="?page={{ page_obj.next_page_number }}{% if sort_by %}&sort_by={{ sort_by }}{% endif %}" rel="next">
                    <span class="govuk-pagination__link-title">
                        Next<span class="govuk-visually-hidden"> page</span>
                    </span>
                    <svg class="govuk-pagination__icon govuk-pagination__icon--next" xmlns="http://www.w3.org/2000/svg" height="13" width="15" aria-hidden="true" focusable="false" viewBox="0 0 15 13">
                        <path d="m8.107-0.0078125-1.4136 1.414 4.2926 4.293h-12.986v2h12.896l-4.1855 3.9766 1.377 1.4492 6.7441-6.4062-6.7246-6.7266z"></path>
                    </svg>
                </a>
            </div>
        {% endif %}
    </nav>

{% endblock column_content %}

{% block extra_js %}
    {{ block.super }}
    <script type="text/javascript" nonce="{{ request.csp_nonce }}">
        $(document).ready(function () {
            $('body').on('click', '.read_more_button', function () {
                $(this).closest('.text_truncator').find('.truncated_text').addClass('hidden');
                $(this).closest('.text_truncator').find('.expanded_text').removeClass('hidden');
            });
            $('body').on('click', '.read_less_button', function () {
                $(this).closest('.text_truncator').find('.truncated_text').removeClass('hidden');
                $(this).closest('.text_truncator').find('.expanded_text').addClass('hidden');
            })
        })
    </script>
{% endblock extra_js %}

django_app/view_a_licence/templates/view_a_licence/unauthorised.html
{% extends "core/base.html" %}
{% block cookie_banner %}{% endblock cookie_banner %}
{% block back_button %}{% endblock back_button %}
{% block title %}Not authorised to View A Licence. Seek approval from the administrator{% endblock title %}
{% block column_content %}
    <div>
        <h1 class="govuk-heading-l">
            Not authorised to View A Licence. Seek approval from the administrator.
        </h1>
    </div>
{% endblock column_content %}

django_app/view_a_licence/templates/view_a_licence/view_all_feedback.html
{% extends "core/base.html" %}
{% block cookie_banner %}{% endblock cookie_banner %}
{% block title %}View Feedback for apply sanctioned services licence{% endblock title %}
{% block back_button %}{% endblock back_button %}
{% block column_content %}
    <div>
        <h1 class="govuk-heading-l">
            View feedback on the apply for a sanctioned services licence service
        </h1>
        <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">
    </div>
    <form method="get" action="{% url 'view_a_licence:view_all_feedback' %}" id="filter_form">
        {% csrf_token %}
        <div class="govuk-form-group">
            <label class="govuk-label" >Created at date minimum (inclusive)</label>
            <input type="date" class="govuk-form" id="created_at_min" name="date_min">
        </div>
        <div class="govuk-form-group">
            <label class="govuk-label">Created at date maximum (inclusive)</label>
            <input type="date" class="form-control" id="created_at_min" name="date_max">
        </div>
        <button type="submit" class="btn btn-primary">Filter</button>

    </form>
    <hr class="govuk-section-break govuk-section-break--m govuk-section-break--visible">

    <h3 class="govuk-heading-s govuk-!-margin-bottom-2">
        <table class="govuk-table govuk-table--small-text-until-tablet">
            <caption class="govuk-table__caption govuk-table__caption--m">Feedback</caption>
            <thead class="govuk-table__head">
                <tr class="govuk-table__row">
                    <th scope="col" class="govuk-table__header"> ID </th>
                    <th scope="col" class="govuk-table__header">Created at</th>
                    <th scope="col" class="govuk-table__header">Modified at </th>
                    <th scope="col" class="govuk-table__header">Rating</th>
                    <th scope="col" class="govuk-table__header">Did you experience any issues? </th>
                    <th scope="col" class="govuk-table__header">How could we improve the service? </th>
                    <th scope="col" class="govuk-table__header">URL </th>
                    <th scope="col" class="govuk-table__header">Agreed to feedback </th>
                </tr>
            </thead>
            <tbody class="govuk-table__body">
                {% for feedback_item in object_list %}
                    <tr class="govuk-table__row">
                        <td class="govuk-table__cell"><a href="{% url 'view_a_licence:view_feedback' pk=feedback_item.id %}">{{ feedback_item.id }}</a></td>
                        <td class="govuk-table__cell">{{ feedback_item.created_at }}</td>
                        <td class="govuk-table__cell">{{ feedback_item.modified_at }}</td>
                        <td class="govuk-table__cell">{{ feedback_item.get_rating_display}} </td>
                        <td class="govuk-table__cell">{{ feedback_item.get_did_you_experience_any_issues_display | linebreaksbr }}</td>
                        <td class="govuk-table__cell">{{ feedback_item.how_we_could_improve_the_service }}</td>
                        <td class="govuk-table__cell">{{ feedback_item.url }}</td>
                        <td class="govuk-table__cell">{% if feedback_item.user_name or feedback_item.user_email %}Yes{% else %}No{% endif %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
{% endblock column_content %}

{% block extra_js %}
    {{ block.super }}
    <script type="text/javascript" nonce="{{ request.csp_nonce }}">
        $(document).ready(function () {
            $('body').on('click', '.read_more_button', function () {
                $(this).closest('.text_truncator').find('.truncated_text').addClass('hidden');
                $(this).closest('.text_truncator').find('.expanded_text').removeClass('hidden');
            });
            $('body').on('click', '.read_less_button', function () {
                $(this).closest('.text_truncator').find('.truncated_text').removeClass('hidden');
                $(this).closest('.text_truncator').find('.expanded_text').addClass('hidden');
            })
        })
    </script>
{% endblock extra_js %}

django_app/view_a_licence/templates/view_a_licence/view_feedback.html
{% extends "core/base.html" %}

{% block title %}View individual feedback{% endblock title %}

{% block column_content %}
    <table class="govuk-table">
        <caption class="govuk-table__caption govuk-table__caption--m">Feedback item - {{ feedback.id }}</caption>
        <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">Created at</th>
                <td class="govuk-table__cell">{{ feedback.created_at }}</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">Rating</th>
                <td class="govuk-table__cell">{{ feedback.get_rating_display}}</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">Issues</th>
                <td class="govuk-table__cell">{{ feedback.get_did_you_experience_any_issues_display | linebreaksbr }}</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">Improvements</th>
                <td class="govuk-table__cell">{{ feedback.how_we_could_improve_the_service }}</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">URL</th>
                <td class="govuk-table__cell">{{ feedback.url }}</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">User name</th>
                <td class="govuk-table__cell">{{ feedback.user_name }}</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">User email</th>
                <td class="govuk-table__cell">{{ feedback.user_email }}</td>
            </tr>
        </tbody>
    </table>
{% endblock column_content %}