django_app/authentication/urls.py
from django.urls import path

from .views import AuthCallbackView, AuthView, LogoutView, SessionExpiredView

app_name = "authentication"
urlpatterns = [
    path("login/", AuthView.as_view(), name="login"),
    path("callback/", AuthCallbackView.as_view(), name="callback"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("session-expired/", SessionExpiredView.as_view(), name="session_expired"),
]

django_app/core/urls.py
import logging

from django.conf import settings
from django.contrib import admin
from django.urls import include, path

from .views import cookie_views, generic_views
from .views.generic_views import PingSessionView, RedirectBaseDomainView

public_urls = [
    path("", RedirectBaseDomainView.as_view(), name="initial_redirect_view"),
    path("give-feedback/", include("feedback.urls")),
    path("healthcheck/", include("healthcheck.urls")),
    path("throw_error/", lambda x: 1 / 0),
    path("apply/", include("apply_for_a_licence.urls")),
    path("cookies-policy", cookie_views.CookiesConsentView.as_view(), name="cookies_consent"),
    path("privacy-notice", generic_views.PrivacyNoticeView.as_view(), name="privacy_notice"),
    path("hide_cookies", cookie_views.HideCookiesView.as_view(), name="hide_cookies"),
    path("reset_session", generic_views.ResetSessionView.as_view(), name="reset_session"),
    path("ping_session/", PingSessionView.as_view(), name="ping_session"),
    path("accessibility-statement", generic_views.AccessibilityStatementView.as_view(), name="accessibility_statement"),
    path("help-support", generic_views.HelpAndSupportView.as_view(), name="help_and_support"),
    path("staff-sso/", include("authbroker_client.urls")),
    path("authentication/", include("authentication.urls")),
]

private_urls = [
    path("view/", include("view_a_licence.urls")),
]

if settings.SHOW_ADMIN_PANEL:
    private_urls.append(path("admin/", admin.site.urls))

if settings.INCLUDE_PRIVATE_URLS:
    logging.info("Include private urls")
    urlpatterns = public_urls + private_urls
else:
    logging.info("Excluding private urls")
    urlpatterns = public_urls

if "debug_toolbar" in settings.INSTALLED_APPS:
    # checking if we have debug_toolbar installed
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

django_app/apply_for_a_licence/views/base_views.py
from typing import Any

from core.views.base_views import BaseSaveAndReturnModelFormView
from django.db import models
from django.forms import Form
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import Http404


class EntityView(BaseSaveAndReturnModelFormView):
    @property
    def pk_url_kwarg(self) -> str:
        if self.model:
            return f"{self.model.__name__.lower()}_id"
        else:
            raise NotImplementedError("You need to implement the model property")

    @property
    def model(self) -> models.Model:
        raise NotImplementedError("You need to implement the model property")

    @property
    def object(self) -> Any:
        try:
            pk = int(self.kwargs[self.pk_url_kwarg])
        except KeyError:
            raise Http404()

        try:
            child_object = self.model.objects.get(
                pk=pk,
                licence=self.licence_object,
            )
        except self.model.DoesNotExist:
            raise Http404()
        return child_object


class AddAnEntityView(EntityView):
    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.object
        return kwargs

    def save_form(self, form: Form) -> Form:
        instance = form.save(commit=False)
        instance.licence = self.licence_object
        instance.save()
        return instance

    @property
    def redirect_after_post(self) -> bool:
        # if ?change is yes, then we want to redirect them to the next step, except for when we're not redirecting
        # them with query parameters, because in that case we've said to ourselves that we're not going to redirect
        if self.request.GET.get("change") == "yes" and self.redirect_with_query_parameters:
            # if we are creating a new one, then we want to take them to the next step
            return False
        else:
            return True


class DeleteAnEntityView(EntityView):
    """Base view for deleting an entity from the database. This is used for infinitely looping sub-journeys, such as
    add a business/recipient/individual."""

    allow_zero_entities = False

    def post(self, request: HttpRequest, *args: object, **kwargs: object) -> HttpResponse:
        entities = self.model.objects.filter(licence=self.licence_object)
        if self.allow_zero_entities or len(entities) > 1:
            self.object.delete()
            return HttpResponseRedirect(self.get_next_url())
        else:
            raise Http404()

django_app/core/views/base_views.py
import datetime
import re
from typing import Any

from apply_for_a_licence.models import Licence
from apply_for_a_licence.utils import can_user_edit_licence
from authentication.mixins import LoginRequiredMixin
from core.forms.base_forms import BaseForm, BaseModelForm
from django.conf import settings
from django.forms import Form
from django.http import (
    Http404,
    HttpRequest,
    HttpResponse,
    HttpResponseBase,
    HttpResponseRedirect,
)
from django.shortcuts import redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils import timezone
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.safestring import mark_safe
from django.views import View
from django.views.generic import DetailView, FormView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from playwright.sync_api import PdfMargins, sync_playwright


class BaseView(LoginRequiredMixin, View):
    def dispatch(self, request: HttpRequest, *args: object, **kwargs: object) -> HttpResponseBase:
        if last_activity := request.session.get(settings.SESSION_LAST_ACTIVITY_KEY, None):
            now = timezone.now()
            last_activity = datetime.datetime.fromisoformat(last_activity)
            # if the last recorded activity was more than the session cookie age ago, we assume the session has expired
            if now > (last_activity + datetime.timedelta(seconds=settings.SESSION_COOKIE_AGE)):
                return redirect(reverse("authentication:logout"))

        # now setting the last active to the current time
        request.session[settings.SESSION_LAST_ACTIVITY_KEY] = timezone.now().isoformat()
        return super().dispatch(request, *args, **kwargs)


class BaseTemplateView(BaseView, TemplateView):
    pass


class BaseSaveAndReturnView(BaseView):
    @property
    def licence_object(self) -> Licence | None:
        if licence_id := self.kwargs.get("licence_pk", None):
            try:
                licence = Licence.objects.get(pk=licence_id)
                if not can_user_edit_licence(self.request.user, licence):
                    raise Http404()
                else:
                    self._licence_object = licence
                    return licence
            except Licence.DoesNotExist:
                return None
        else:
            return None


class BaseSaveAndReturnFormView(BaseSaveAndReturnView, FormView):
    template_name = "core/base_form_step.html"
    # do we want to redirect the user to the redirect_to query parameter page after this form is submitted?
    redirect_after_post = True

    # do we want to redirect the user to the next step with query parameters?
    redirect_with_query_parameters = False

    def dispatch(self, request: HttpRequest, *args: object, **kwargs: object) -> HttpResponse:
        if self.request.GET.get("update", None) == "yes":
            self.update = True
        else:
            self.update = False

        return super().dispatch(request, *args, **kwargs)

    def post(self, request: HttpRequest, *args: object, **kwargs: object) -> HttpResponse:
        if self.request.POST.get("skip_link"):
            if self.licence_object:
                return HttpResponseRedirect(reverse("tasklist", kwargs={"licence_pk": self.licence_object.id}))
            else:
                return HttpResponseRedirect(reverse("dashboard"))
        else:
            return super().post(request, *args, **kwargs)

    def get_form(self, form_class: BaseForm | None = None) -> BaseForm:
        form = super().get_form(form_class)
        self.form = form
        return form

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

    def form_valid(self, form: Form) -> HttpResponse:
        return HttpResponseRedirect(self.get_next_url())

    def get_next_url(self) -> str:
        """Get the URL of the next page, could either be the next step, tasklist, or a redirect_to.

        We abstract this to another method so that views can call it without having to use/re-use form_valid"""
        # figure out if we want to redirect after form is submitted
        redirect_to_url = self.request.GET.get("redirect_to_url", None) or self.request.session.pop("redirect_to_url", None)
        if redirect_to_url and url_has_allowed_host_and_scheme(redirect_to_url, allowed_hosts=None):
            if self.redirect_after_post:
                if self.licence_object:
                    # we want to redirect the user to a specific page after the form is submitted
                    return reverse(redirect_to_url, kwargs={"licence_pk": self.licence_object.id})
                else:
                    return reverse("dashboard")
            else:
                # we don't want to redirect the user just now, but we want to pass the redirect_to URL to the next form,
                # so it can redirect the user after it is submitted
                self.request.session["redirect_to_url"] = redirect_to_url

        success_url = self.get_success_url()
        if self.redirect_with_query_parameters:
            success_url = self.add_query_parameters_to_url(success_url)

        return success_url

    def add_query_parameters_to_url(self, success_url: str) -> str:
        """Add GET query parameters to the success URL so they're retained."""
        if get_parameters := self.request.GET.urlencode():
            updated_parameters = re.sub(r"(business|yourself|individual|recipient)_id=\d+&?", "", get_parameters)
            if updated_parameters:
                success_url += "?" + updated_parameters
        return success_url

    def get_context_data(self, **kwargs: object) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if licence := self.licence_object:
            context["licence"] = licence
            context["skip_link"] = self.request.session.get("skip_link", False)
        return context


class BaseSaveAndReturnModelFormView(SingleObjectMixin, BaseSaveAndReturnFormView):
    def get_form(self, form_class=None) -> BaseModelForm:
        form = super().get_form(form_class)
        self.form: BaseModelForm = form
        return form

    def form_valid(self, form: Form) -> HttpResponse:
        self.instance = self.save_form(form)
        return super().form_valid(form)

    def save_form(self, form: Form) -> Form:
        return form.save()


class BaseSaveAndReturnLicenceModelFormView(BaseSaveAndReturnModelFormView):
    @property
    def object(self):
        return self.licence_object

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.object
        return kwargs


class BaseDownloadPDFView(DetailView):
    template_name = "core/base_download_pdf.html"
    header = "Apply for a licence to provide sanctioned trade services"

    def get(self, request: HttpRequest, **kwargs: object) -> HttpResponse:
        self.reference = self.request.GET.get("reference", "")
        filename = f"application-{self.reference}.pdf"
        pdf_data = None
        template_string = render_to_string(self.template_name, context=self.get_context_data(**kwargs))
        margins = PdfMargins(left="1.25in", right="1.25in", top="1in", bottom="1in")

        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(headless=True)
            page = browser.new_page()
            page.set_content(mark_safe(template_string))
            page.wait_for_function("document.fonts.ready.then(fonts => fonts.status === 'loaded')")
            pdf_data = page.pdf(format="A4", tagged=True, margin=margins)
            browser.close()

        response = HttpResponse(pdf_data, content_type="application/pdf")
        response["Content-Disposition"] = f"inline; filename={filename}"
        return response

    def get_context_data(self, **kwargs: object) -> dict[str, Any]:
        self.object: list[Any] = []
        context = super().get_context_data(**kwargs)
        context["header"] = self.header
        context["reference"] = self.reference
        return context

django_app/core/views/cookie_views.py
from typing import Any

from core.forms.cookie_forms import CookiesConsentForm, HideCookiesForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import FormView


class CookiesConsentView(FormView):
    template_name = "core/cookies_consent.html"
    form_class = CookiesConsentForm

    def dispatch(self, request: HttpRequest, *args: object, **kwargs: object) -> HttpResponse:
        # storing where we want to redirect
        # the user back to the page they were on before they were shown the cookie consent form
        if redirect_back_to := self.request.GET.get("redirect_back_to"):
            self.request.session["redirect_back_to"] = redirect_back_to
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self) -> dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request

        if current_cookies_policy := self.request.COOKIES.get("accepted_ga_cookies"):
            initial_dict = {"accept_cookies": current_cookies_policy == "true"}
            kwargs["initial"] = initial_dict

        return kwargs

    def form_valid(self, form: CookiesConsentForm) -> HttpResponse:
        # cookie consent lasts for 1 year
        cookie_max_age = 365 * 24 * 60 * 60

        if "came_from_cookies_page" in self.request.GET:
            response = redirect(reverse("cookies_consent") + "?cookies_set=true")
        else:
            redirect_url = self.request.session.get("redirect_back_to", "/")

            # checking if the redirect url already has a query string
            if "?" in redirect_url:
                redirect_url += "&"
            else:
                redirect_url += "?"
            redirect_url += "cookies_set=true"
            response = redirect(redirect_url)

        # regardless of their choice, we set a cookie to say they've made a choice
        response.set_cookie("cookie_preferences_set", "true", max_age=cookie_max_age)
        response.set_cookie(
            "accepted_ga_cookies",
            "true" if form.cleaned_data["do_you_want_to_accept_analytics_cookies"] else "false",
            max_age=cookie_max_age,
        )
        return response


class HideCookiesView(FormView):
    template_name = "core/hide_cookies.html"
    form_class = HideCookiesForm

    def form_valid(self, form: HideCookiesForm) -> HttpResponse:
        referrer_url = self.request.session.get("redirect_back_to", "/")
        if "cookies_set" in referrer_url:
            referrer_url = referrer_url.replace("?cookies_set", "?removed_cookies_set")
            referrer_url = referrer_url.replace("&cookies_set", "&removed_cookies_set")
        return redirect(referrer_url)

django_app/core/views/generic_views.py
from core.sites import is_apply_for_a_licence_site, is_view_a_licence_site
from core.utils import update_last_activity_session_timestamp
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views import View
from django.views.generic import RedirectView, TemplateView


class ResetSessionView(View):
    """Resets and clears the users session"""

    def get(self, request: HttpRequest) -> HttpResponse:
        request.session.flush()
        return redirect("initial_redirect_view")


class PrivacyNoticeView(TemplateView):
    template_name = "core/privacy_notice.html"


class AccessibilityStatementView(TemplateView):
    template_name = "core/accessibility_statement.html"


class HelpAndSupportView(TemplateView):
    template_name = "core/help_and_support.html"


class PingSessionView(View):
    """Pings the session to keep it alive"""

    def get(self, request: HttpRequest) -> HttpResponse:
        update_last_activity_session_timestamp(request)
        return HttpResponse("pong")


class RedirectBaseDomainView(RedirectView):
    """Redirects base url visits to either apply-for-a-licence or view-a-licence default view"""

    @property
    def url(self) -> str:
        if is_apply_for_a_licence_site(self.request.site):
            return reverse("dashboard")
        elif is_view_a_licence_site(self.request.site):
            return reverse("view_a_licence:application_list")
        return ""

django_app/core/templates/core/accessibility_statement.html
{% extends "core/base.html" %}
{% load crispy_forms_tags crispy_forms_gds %}
{% block meta %}<meta name="Accessibility statement – Apply for a licence to provide sanctioned trade services – GOV.UK" content="Information about the accessibility of the ‘Apply for a licence to provide sanctioned trade services’ service."> {% endblock meta %}
{% block title %}Accessibility statement{% endblock title %}
{% block column_content %}

    <h1 class="govuk-heading-l">Accessibility statement</h1>
    <p class="govuk-body">This statement applies to the ‘Apply for a licence to provide sanctioned trade services’ service.  </p>
    <p class="govuk-body">This service is part of the wider GOV.UK website. There's a separate <a href="https://www.gov.uk/help/accessibility-statement/" class="govuk-link">accessibility statement for the main GOV.UK website</a>.</p>
    <p class="govuk-body">This service is run by the Department for Business and Trade (DBT). We want as many people as possible to use it. For example, that means you should be able to:  </p>
    <ul class="govuk-list govuk-list--bullet">
        <li>change colours, contrast levels and fonts</li>
        <li>zoom in up to 200% without the text spilling off the screen</li>
        <li>get from the start of the service to the end using just a keyboard or speech recognition software</li>
        <li>listen to the service using a screen reader (including the most recent versions of JAWS, NVDA and VoiceOver)</li>
    </ul>
    <p class="govuk-body">We’ve also made the website text as simple as possible to understand.</p>
    <p class="govuk-body"><a href="https://mcmw.abilitynet.org.uk" class="govuk-link">AbilityNet</a>
        has advice on making your device easier to use if you have a disability.</p>

    <h2 class="govuk-heading-m">Feedback and contact information</h2>
    <p class="govuk-body">If you need accessibility support to access this service, email
        <a href="mailto:OTSI@businessandtrade.gov.uk" class="govuk-link">OTSI@businessandtrade.gov.uk</a>.</p>
    <p class="govuk-body">If you find any problems not listed on this page or think we do not meet accessibility requirements, contact us. We’ll consider your request and get back to you within 20 days.</p>

    <h2 class="govuk-heading-m">Enforcement procedure</h2>
    <p class="govuk-body">The Equality and Human Rights Commission (EHRC) is responsible for enforcing the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018 (the ‘accessibility regulations’). If you’re not happy with how we respond to your complaint, <a href="https://www.gov.uk/equality-advisory-support-service/" class="govuk-link">contact the Equality Advisory and Support Service (EASS)</a>.</p>

    <h2 class="govuk-heading-m">Technical information about the accessibility of this service</h2>
    <p class="govuk-body">DBT is committed to making this service accessible, in accordance with the Public Sector Bodies (Websites and Mobile Applications) (No. 2) Accessibility Regulations 2018.</p>

    <h3 class="govuk-heading-s">Compliance status</h3>
    <p class="govuk-body">This service is fully compliant with the
        <a href="https://www.w3.org/TR/WCAG22/" class="govuk-link">Web Content Accessibility Guidelines (WCAG)</a>
        version 2.2 AA standard.</p>

    <h3 class="govuk-heading-s">Content that is not within the scope of the accessibility regulations</h3>
    <p class="govuk-body">There are some usability issues that fall outside the scope of the UK accessibility regulations. These include:</p>
    <ul class="govuk-list govuk-list--bullet">
        <li>some of the colour combinations do not meet enhanced contrast ratios and may be difficult for people with colour vision deficiency to read</li>
        <li>error prevention is low in some places, which means users may accidentally submit incorrect information</li>
        <li>users of speech recognition software may find it difficult to start a file upload, and may need to use keyboard or mouse commands instead</li>
        <li>when an error message appears, keyboard users may not be able to skip straight from the error summary to the input field where the error occurred</li>
        <li>some error messages do not fully describe the error that occurred and how to fix it</li>
    </ul>
    <h2 class="govuk-heading-m">Preparation of this accessibility statement</h2>
    <p class="govuk-body">This statement was prepared on 23 September 2024. It was last reviewed on 13 November 2024.</p>
    <p class="govuk-body">This service was last tested on 2 September 2024 against the WCAG 2.2 AA standard. The test was carried out by the
        <a href="https://digitalaccessibilitycentre.org/" class="govuk-link">Digital Accessibility Centre (DAC)</a>.</p>

{% endblock column_content %}

django_app/core/templates/core/base_download_pdf.html
{% extends "core/base.html" %}
{% load get_css_rules_as_string %}
{% block cookie_banner %}
{% endblock cookie_banner %}
{% block header_image_link %}
{% endblock header_image_link %}
{% block header_content %}
{% endblock header_content %}
{% block skip_link %}{% endblock skip_link %}
{% block phase_banner %}{% endblock phase_banner %}
{% block back_button %}{% endblock back_button %}
<script>
    {% get_css_rules_as_string "core/stylesheets/font-awesome-6.5.2.css" %}
    {% get_css_rules_as_string "core/stylesheets/govuk-frontend-5.3.0.min.css" %}
    {% get_css_rules_as_string "core/stylesheets/common.css" %}
</script>
{% block footer %}{% endblock footer %}

django_app/core/templates/core/base_form_step.html
{% extends "core/base_logged_in_template.html" %}
{% load crispy_forms_tags crispy_forms_gds static %}

{% block extra_css %}
    {{ form.media.css }}
{% endblock extra_css %}

{% block title %}
    {% if form.errors %}
        Error:
    {% endif %}
    {% if form.form_h1_header %}
        {{ form.form_h1_header }}
    {% else %}
        {% for field in form %}
            {% if forloop.first %}
                {{ field.label }}
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock title %}

{% block column_content %}
    {% error_summary form %}
    <form action="{% block form_action %}{{ request.get_full_path }}{% endblock form_action %}" method="post" enctype='multipart/form-data' novalidate>
        {% if form.form_h1_header %}
            <h1 class="govuk-heading-l">{{ form.form_h1_header }}</h1>
        {% endif %}
        {% csrf_token %}
        {% block form_content %}
            {% crispy form %}
            <div class="govuk-button-group">
                <button type="submit" class="govuk-button" data-module="govuk-button">
                    Save and continue
                </button>
                {% if skip_link %}
                    <a class="govuk-link govuk-link--no-visited-state govuk-!-margin-left-4" href="{% url 'tasklist' licence_pk=licence.id %}">Skip for now and return to task list</a>
                {% endif %}
            </div>

        {% endblock form_content %}
    </form>
{% endblock column_content %}

{% block extra_js %}
    {{ block.super }}
    {{ form.media.js }}
{% endblock extra_js %}

django_app/core/templates/core/cookies_consent.html
{% extends "core/base.html" %}
{% load crispy_forms_tags crispy_forms_gds %}

{% block title %}Cookies{% endblock title %}
{% block column_content %}
    {% if "cookies_set" in request.GET %}
        <div class="govuk-notification-banner govuk-notification-banner--success" role="alert"
             aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
            <div class="govuk-notification-banner__header">
                <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
                    Success
                </h2>
            </div>
            <div class="govuk-notification-banner__content">
                <p class="govuk-notification-banner__heading">
                    You’ve set your cookie preferences.
                    <a class="govuk-notification-banner__link"
                       href="{{ request.session.redirect_back_to|default_if_none:"/?start=true" }}">
                        Go back to the page you were looking at
                    </a>.
                </p>
            </div>
        </div>
    {% endif %}
    <h1 class="govuk-heading-xl">Cookies on Apply for a licence to provide sanctioned trade services</h1>

    <p class="govuk-body">Cookies are small files saved on your phone, tablet or computer when you visit a website.</p>

    <p class="govuk-body">We use cookies to make this service work and collect information about how you use it.</p>

    <h2 class="govuk-heading-l govuk-!-margin-top-6">Essential cookies</h2>

    <p class="govuk-body">Essential cookies keep your information secure while you use this service. We do not need to ask permission to use them.</p>

    <table class="govuk-table">
        <thead class="govuk-table__head">
            <tr class="govuk-table__row">
                <th scope="col" class="govuk-table__header">Name</th>
                <th scope="col" class="govuk-table__header">Purpose</th>
                <th scope="col" class="govuk-table__header">Expires</th>
            </tr>
        </thead>
        <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">accepted_ga_cookies</th>
                <td class="govuk-table__cell">Saves your cookie consent settings.</td>
                <td class="govuk-table__cell">1 year</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">cookie_preferences_set</th>
                <td class="govuk-table__cell">Lets us know that you’ve saved your cookie consent settings.</td>
                <td class="govuk-table__cell">1 year</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">csrftoken</th>
                <td class="govuk-table__cell">Allows us to verify that form submissions come from this service and have not been forged by a third party.</td>
                <td class="govuk-table__cell">1 year</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">sessionid</th>
                <td class="govuk-table__cell">Tracks your session to ensure basic website functionality.</td>
                <td class="govuk-table__cell">15 minutes</td>
            </tr>
        </tbody>
    </table>


    <h2 class="govuk-heading-l govuk-!-margin-top-6">Analytics cookies (optional)</h2>

    <p class="govuk-body">With your permission, we use Google Analytics to collect data about how you use this service. This information helps us to improve it.</p>

    <p class="govuk-body">We do not allow Google to use or share our analytics data.</p>

    <p class="govuk-body">Google Analytics stores anonymised information about:</p>

    <ul class="govuk-list govuk-list--bullet">
        <li>how you got to this service</li>
        <li>the pages you visit in this service and how long you spend on them</li>
        <li>any errors you see while using this service</li>
    </ul>

    <table class="govuk-table">
        <thead class="govuk-table__head">
            <tr class="govuk-table__row">
                <th scope="col" class="govuk-table__header">Name</th>
                <th scope="col" class="govuk-table__header">Purpose</th>
                <th scope="col" class="govuk-table__header">Expires</th>
            </tr>
        </thead>
        <tbody class="govuk-table__body">
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">_ga</th>
                <td class="govuk-table__cell">Helps us count how many people visit this service by tracking if you’ve visited before.</td>
                <td class="govuk-table__cell">2 years</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">_gid</th>
                <td class="govuk-table__cell">Helps us count how many people visit this service by tracking if you’ve visited before.</td>
                <td class="govuk-table__cell">1 day</td>
            </tr>
            <tr class="govuk-table__row">
                <th scope="row" class="govuk-table__header">_gat</th>
                <td class="govuk-table__cell">Used to manage the rate at which page view requests are made.</td>
                <td class="govuk-table__cell">1 minute</td>
            </tr>
        </tbody>
    </table>
    <form method="post" action="{% url 'cookies_consent' %}?came_from_cookies_page=true">
        {% csrf_token %}
        {% crispy form %}
    </form>
{% endblock column_content %}

django_app/core/templates/core/hide_cookies.html
{% extends "core/base.html" %}
{% load crispy_forms_tags crispy_forms_gds %}

{% block form_content %}
  {% block column_content %}
    {% csrf_token %}
    {% crispy form %}
  {% endblock column_content %}
{% endblock form_content %}

django_app/core/templates/core/session_expired.html
{% extends "core/base.html" %}

{% block back_button %}{% endblock back_button %}

{% block title %}You've been signed out{% endblock title %}

{% block column_content %}
    <h1 class="govuk-heading-l">You've been signed out</h1>
    <p class="govuk-body">We've signed you out because you were inactive for {{ SESSION_EXPIRY_MINUTES }} minutes.</p>
    <p class="govuk-body">Any information you did not save has been deleted for your security.</p>
    <p class="govuk-body">To continue your application, you'll need to sign in again.</p>

    <a class="govuk-button" href="{% url "authentication:callback" %}" data-testid="sign_in_link">Sign in</a>
{% endblock column_content %}